### ISSUE TITLE
1.17.1: Gradients Require Relog

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#10]
NameGradients require a relog before they appear, All other colors do work instantly (including hex and default colors)
ChatGradients also seem to work fine

**Comment by UltimateGamer200** [comment]
I've done some testing on 1.16.5 (I can't do 1.17 because I'm not quite ready to update my computer to Java 16 since I have other dev projects for a network on 1.16.5) and I don't see the issue. I was able to select name gradients and they appeared instantly. Though this test was done on a jar I'm currently working on, so I would recommend testing this when the next update is released. For now, I'll leave this open in case the next update doesn't fix it.

**Comment by mesl** [comment]
Thank you very much!
If you can, Maybe also test gradients while already having another color selected, since that seems to bug out for me as well

**Comment by UltimateGamer200** [comment]
Interesting. Will take a look into this at some point soon.
