### ISSUE TITLE
1.17.1: Extreme lag

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#13]
Changed the server world, Extreme lag occurs now, Did a timings to see why, this is the result:

https://imgur.com/a/lGH2mAf

https://timings.aikar.co/?id=0b8b0fd6a3554e4b9221846697c87d9a
full timings

Hope you can help!
Kind regards, Merlyn

**Comment by UltimateGamer200** [comment]
It looks like the tab-completing of nicknames is causing this. I tried making this happen asynchronously, but that only removes the nickname tabbing completely. Looks like this will have to be removed in the next update. Plus, even if you use nicknames in the commands instead of player names in player arguments without the tab completion, it'll replace that nickname with the real player name so other plugins can recognize it. So it wouldn't be a big loss for the removal of this feature. Thanks for bringing this to my attention!

**Comment by mesl** [comment]
Is there any way I can turn this off now? 1/2 times a player performs a command that includes names the server crashes lol

**Comment by UltimateGamer200** [comment]
There is no current way of disabling this, but I do have a test jar you can use for now that's already been made prior to today. This jar removes this tab feature completely except for /realname command. You can download this here: https://ufile.io/sp193h5k! 

Cheers!

**Comment by mesl** [comment]
Thank you a lot!
