### ISSUE TITLE
Error clicking in menu GradientMenu needs your help

### ISSUE THREAD

**Issue by Zz-886** [UltimateGamer200/UltraColor#4]
Error log:https://pastebin.com/raw/n6PgezPp
![image](https://user-images.githubusercontent.com/55978588/124345755-4e395d80-dc0d-11eb-8bf8-261b77386568.png)

**Comment by UltimateGamer200** [comment]
From what I see in this exception, this is saying that one of the slots is over the maximum the menu size allows (by menu, I mean the menu you're trying to open while interacting with the main gradient menu). I have a potential idea on how to fix this since this is complaining about index 17 (slot 17).

Could you try going into your messages file, find the Return section under Gradient_Color_Selection_Customization, and change the slot to a number that's between 0-8 (because the menu size is 9) and isn't one of the previous menu item's slots (for instance, if the custom name gradient menu item has a slot of 0, don't change the return button slot to 0 otherwise it'll override the custom name gradient button)?

Hopefully, that helps!

**Comment by Zz-886** [comment]
The problem has been resolved, thank you for your reply.
But the gradient will be applied to the chat, and I cannot reset my gradient
![image](https://user-images.githubusercontent.com/55978588/124371095-18e64b80-dcb1-11eb-9524-c5530f11599d.png)

**Comment by UltimateGamer200** [comment]
I think I found why that's the case. Misconfiguration in coding.

Testing has proven this bug to be fixed. This bug fix will be in the next update I release hopefully soon!

Feel free to try out the next update when it's released and let me know if it's fixed!

**Comment by Zz-886** [comment]
Ok thanks

**Comment by UltimateGamer200** [comment]
I'm pretty sure the latest version (1.3.0) fixes the bugs mentioned here, so feel free to give it a try! If it doesn't fix the bugs mentioned here for whatever reason, then please reach out to me on Spigot or Discord (Ultimation#1600) as I'll be closing this issue ticket now.

Hopefully, it's all fixed!
