### ISSUE TITLE
Two functional issues

### ISSUE THREAD

**Issue by Zz-886** [UltimateGamer200/UltraColor#6]
UltraColor setting color and format cannot overwrite Chat Manager
Menu lnformation No translation
![image](https://user-images.githubusercontent.com/55978588/130048692-0aeaaf9f-c696-4a6e-b2b4-9b48917f3878.png)

**Comment by Zz-886** [comment]
I changed the Change in CMI from false to false. The name is normal, but the chat color is not displayed normally.

**Comment by Zz-886** [comment]
I changed the Change under DisplayName in CMI to false. The name is displayed normally, but the chat color cannot be displayed.

**Comment by UltimateGamer200** [comment]
So let me get this straight. You're saying that the Menu Information title translation isn't provided and that chat color isn't being displayed? I'm currently at school so responses will be delayed.

**Comment by Zz-886** [comment]
Only the icon lore translation option in messages
Chat color cannot be applied

**Comment by UltimateGamer200** [comment]
What chat manager plugin are you using? I've been testing with ChatManager on 1.16.5 and it's applying chat colors perfectly. Also, what version of UltraColor are you using?

**Comment by Zz-886** [comment]
I'm also so ChatManager
UltraColor version: 1.3.4

**Comment by UltimateGamer200** [comment]
Hm, okay. Might be a good idea to send your ChatManager config so when I get home from school, I'll have a chance to look at it and do some experimenting.

**Comment by UltimateGamer200** [comment]
Also, are you using Vault?

**Comment by Zz-886** [comment]
Yes i am using Vault
[config.zip](https://github.com/UltimateGamer200/UltraColor/files/7014848/config.zip)

**Comment by UltimateGamer200** [comment]
I did some experimenting and I found a solution for you (turns out, I wasn't using ChatManager. I mentioned I did because I'm using it on the network I'm Developer/Co-Owner of, so my bad). The plugin provides chat/name color placeholders for cases like yours's where the coloring and formatting we do doesn't entirely like a plugin like ChatManager. To fix your second issue, you'll need to go into the config you sent me and add the **%ucolor_chat_color%** placeholder before each of the {message}'s you intend to have player's chat coloring/formatting for. 

For the first one, I'll need to add that as an item for the next update, which isn't too big right now, so it shouldn't be too crazy long.

Let me know how it works! I attached an example config incase you need it.
[config.zip](https://github.com/UltimateGamer200/UltraColor/files/7018043/config.zip)

**Comment by UltimateGamer200** [comment]
Since you haven't mentioned anything in about 2 days, I'm going to assume this issue has been fixed and close this ticket. If it's not, reach out to me via Discord (Ultimation#1600) or Spigot next Thursday (I'm taking time off due to a family member of mine passing and to get back into things with school).

Also, feel free to update to 1.3.5 as that update contains your suggestion of the menu information title being modified and translated!
