### ISSUE TITLE
1.17.1 | EssentialsChat Formatting

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#7]
Hello! I recently installed this plugin, but namecolor is not changing, I am aware that this is caused by essentialschat, Yet I use essentialschat to format my prefixes. Is there any way I can fix the namecolors working without disabling the change-displayname?

Thank you very much & Hope to hear back from you
Merlyn

**Comment by UltimateGamer200** [comment]
Hello!

At the current moment, there is no way for you to fix this without disabling the change-displayname. This is because, for a person's name color to be displayed, the player's display name needs to be changed, and that option you mentioned when set to true prevents that from happening. However, you should still be able to use EssentialsChat for prefix formatting as that isn't a part of the player's display name (it's a part of chat formatting).

Hope this helps!

**Comment by mesl** [comment]
Thank you very much for your response!

This makes sense, I have disabled the option and now the namecolor shows, I just need to figure out how to make the prefixes (with hex) work!

Thank you and kind regards,
Merlyn
