### ISSUE TITLE
Independent name/chat format

### ISSUE THREAD

**Issue by mesl** [UltimateGamer200/UltraColor#8]
Have a seperate command to format the players' name or chat independently from color, right now you can set for example a players' format by /ucolor forcecolor name %player% {color} {format}

I'd like to be able to set a players format without the {color}, so something along the lines of /ucolor forceformat %player% {format}

Another (maybe easier way to implement this is to add a 'current' value that can fit in the {color} variable, this value would take the current color and pass it on again

Would this be possible to implement?
If you need more info feel free to ask!

Thank you and kind regards,
Merlyn

**Comment by UltimateGamer200** [comment]
Hello again!

I took a look at the forcecolor command you mentioned and there is a way you can set a format without color via that command. You just need to put "none" in place of the {color} argument and then specify the format you want to force on someone. The reason that command works this way is to save size on the plugin jar and to also maybe make it a little easier to remember commands. Hopefully, that makes sense, and feel free to add more info I'm not seeing!

Thanks,
UltimateGamer200

P.S: Do expect a delay now until sometime tomorrow morning/afternoon in responses since it's about 1:30 am for me.

**Comment by mesl** [comment]
Hello!

Thank you for your response!

I was unaware of the 'none' but thank you very much for enlightening me!

Thank you and kind regards,
Merlyn

Also: Goodnight!

**Comment by mesl** [comment]
Hello!
Sorry for reopening this, but it appears that this command does not work for gradients (predefined at least)
For example, If the user has a gradient and then selects a format with the command the format will show but the gradient will dissappear

Hope you can help me
Thank you and kind regards,
Merlyn

**Comment by UltimateGamer200** [comment]
Hello! 

There is another admin command called `/ucolor forcegradient` where you'll be able to force gradients on another player (it needs what type of gradient to force either name or chat, the player to force it to, the first hex color of the gradient, and the second hex color of the gradient. You can also set an optional format if you want). I do though see that the format doesn't show when forcing a name gradient, which I believe I fixed now.
